== Problemstellung ==

=== Einleitung ===
Eine überschneidungsfreie Lehrveranstaltungsplanung liegt sowohl im Interesse der Studierenden als auch im Interesse
der Lehrenden bzw. der Institute.
Diese Projektarbeit beschreibt die Entstehung, dessen Probleme und evtl. zukünftige Möglichkeiten einer Applikation,
welche es ermöglicht Terminkollisionen von Lehrveranstaltungen aufzuzeigen und auf Grund dessen die Möglichkeit bietet
gegebenenfalls einzelne Lehrveranstaltungen noch vor Abschluss der Einschreibepflicht zu verlegen.
Als weiteres Feature soll diese Applikation das Planen der künftigen Semester eines Studenten erleichtern.
In beiden Fällen orientiert sich die Applikation an den idealtypischen Studienplänen.

=== Problembeschreibung ===

Es werden folgend zwei Probleme definiert und im Zuge des Projektes ausgearbeitet:

Aus Institutssicht::
Zurzeit kommt es bei der Planung von Lehrveranstaltungen teilweise
zu Überschneidungen von LVA-Terminen. Diese Überschneidungen werden in der Regel erst während des
Lehrveranstaltungsbetriebs bekannt, was eine nachträgliche Änderung erschwert.

Aus Studentensicht::
Die Planung für Kurse eines Semesters gestaltet sich im KUSSS als undurchsichtig und aufwendig.
Sollte man aus div. Gründen einen möglichst Lückenfreien, bzw. komprimierten Stundenplan anstreben, erfordert dies
derzeit im KUSSS einiges an Recherche und manuelle, nicht IT-gestützte Planungsarbeit.


=== Projektziele ===
Es sollen in erster Linie Terminkollisionen von bereits geplanten Lehrveranstaltungen und Klausuren, nach dem
idealtypischen Studienplan des Bachelorstudiums Wirtschaftsinformatik, aufgezeigt werden, um den für die LVA-Planung
verantwortlichen Personen die Möglichkeit zu geben LVA-Kollisionen vor Beginn des Hauptanmeldezeitraums zu beheben.
Weiteres Ziel ist die Unterstützung der Studierenden bei
der Semesterplanung in Form eines Tools, welches die LVAs eines Semesters gemäß idealtypischen Studienplans in
kalendarischer Form darstellt.

=== Vorgehensweise ===

Die Projektorganisation dieses Projektes lässt sich mit einer „Matrix-Projektorganisatin“ aus der Literatur vergleichen.
Die „Matrix-Projektorganisation“ stellt eine Kombination aus der „Einfluss-Projektorganisation“ und der
„Reinen Projektorganisation“ dar. Laut Wieczorrek und Mertens (2001, S. 31 – 33) werden Mitarbeiter in dieser
Organisationsform nicht aus den jeweiligen Abteilungen ausgegliedert, jedoch für die Dauer der Bearbeitung bestimmter
Aufgaben des Projektes zusätzlich dem Projektleiter unterstellt. Der Projektleiter trägt die Verantwortung über die
Erreichung von Zielen und der Einhaltung von Fristen. Durch die Flexibilität der Mitarbeiter können Aufgaben in
verschiedenen Projekten erledigt werden bei welchen eine vollständige Zuteilung aufgrund der Aufgabengröße nicht nötig
ist, ohne größere Umstrukturierungen durchführen zu müssen. Ähnlich wird die Matrix-Projektorganisation von Broy und
Kuhrmann (2013, S. 54- 55) beschrieben. Die Mitarbeiter, gehen sowohl ihren Abteilungstätigkeiten sowie dem Bearbeiten
der Projektaufgaben nach, damit gibt es zwei Führungsorgane, die jeweils eine Weisungsbefugnis besitzen. Durch diese
mehrfache Zuteilung wird die Flexibilität erhöht, da Ressourcen abgezogen oder zugewiesen werden können. Ebenso ist eine
klare Projektleitung möglich, da Verantwortung und Weisungsbefugnis im Projekt klar definiert ist. Dies ist aber nur
möglich, wenn die Abstimmung zwischen den einzelnen Leitern geben ist, da Ressourcen geteilt werden müssen und eine
mögliche Bindung dieser Ressourcen erfolgen kann. Gerade dieser Nachteil kann zu Problemen führen, da ein ständiger
Interessenskonflikt zwischen Abteilungen bzw. verschiedenen Projekten besteht, die bestimmte Ziele erreichen müssen.
Nur durch eine aufwändige Planung lässt sich die Verteilung von Ressourcen wirksam durchführen.

Das Projektteam besteht aus 5 Mitgliedern welche alle in einem aufrechten Dienstverhältnis beschäftigt sind. Eine
Abstimmung zwischen der Projektleitung und den jeweiligen Vorgesetzen ist jedoch in unserem Fall nicht gegeben. Die
Pflichten der Mitglieder gegenüber deren Dienstgeber hat natürlich eine höhere Priorität als die dem Projekt bzw. dem
Projektleiter gegenüber.

Prinzipiell wurde das Projekt in 4 Phasen unterteilt, wobei jede Phase mit der Erreichung der im Projektvertrag
festgelegten Meilensteine abschließt. Zusätzlich wurden im Vorfeld ein Projektplan, ein Strukturplan, ein Netzplan, ein
Qualitätsplan und ein Ressourcenplan für das vorhandene Personal erstellt.

==== Phase 1 – Anforderungsspezifikation (26.6.2017) ====
Die erste Phase des Projektes beschäftigt sich primär mit der Anforderungserhebung. Dazu wurden erst, intern im
Projektteam, mittels Brainstorming einige Ideen gesammelt. Im zweiten Schritt wurden die zuständigen Sekretariate der vier
Wirtschaftsinformatik Institute befragt, um notwendige Funktionalitäten zu erheben. Aufgrund der erhobenen Daten wurde
schlussendlich eine Anforderungsspezifikation erstellt an Hand dessen die Applikation entwickelt werden sollte. Bei der
Erstellung der Anforderungsspezifikation wurde in must-have und nice-to-have Funktionalitäten unterschieden.

==== Phase 2 – Fertigstellung Backend (31.7.2017) ====
In Phase 2 wurde der primäre Fokus auf die Entwicklung eines Berechnungsschemas gelegt um kollidierende
Lehrveranstaltungen bewerten zu können. Die Basis hierfür stammt aus den Gesprächen mit den Instituten.
Gleichzeitig wurde eine geeignete Abfrage erstellt, um alle benötigten Daten aus dem KUSSS exportieren zu können. Am
Ende dieser Phase sollte das Backend fertig gestellt sein.

==== Phase 3 – Basisfunktionalität der Institutsplanung lt. Anforderungsspezifikation (15.8.2017) ====
Nach der Fertigstellung des Backends mit Meilenstein 2 wurde in Phase 3 der Fokus auf die Implementierung der Basis-
Funktionalitäten der Institutsplanung gelegt. Diese Phase wurde mit einem Usability-Test bzw. einer kurzen Präsentation
für alle beteiligten Mitarbeiter der Institute abgeschlossen, um die Benutzbarkeit bzw. Sinnhaftigkeit der
implementierten Funktionen zu gewährleisten.

==== Phase 4 – Institutsplanung in erweiterter Form und Studentenplanung (20.10.2017) ====
Aufbauend auf Phase 3 wurden die Basisfunktionalitäten der Institutsplanung verfeinert bzw. erweitert. Zusätzlich wurde
auch die Studentenansicht lt. Spezifikation umgesetzt.

=== Erwartetes Ergebnis ===
Da keinerlei Erfahrungswerte in Bezug auf die Zusammenarbeit der Mitglieder, sowie des Aufwands vergleichbarer Projekte
vorhanden waren, erwies sich die Planung bzw. die Einschätzung der benötigten Ressourcen als schwierig. Dennoch war sich
das Projektteam einig, zumindest die in der Anforderungsspezifikation definierten must-have Funktionen bis zum
Projektende erfolgreich umsetzen zu können. Hauptaugenmerk wurde auf die Entwicklung und Dokumentation der
Berechnungsgrundlage und des Backends gelegt, damit für evtl. weiterführende Projekte zu diesem Thema eine adäquate
Basis zur Verfügung gestellt werden kann.

=== Erwartete Schwierigkeiten ===
Möglich auftretende Probleme könnten Fehleinschätzungen bzgl. der Ressourcen sein. Zusätzlich sind technische
Schwierigkeiten nicht auszuschließen. Zum Zeitpunkt des Projektstarts waren jedoch keine Schwierigkeiten zu erwarten,
welche zu einem erfolglosen Abschluss des Projektes führen könnten.

