== Reflexion ==

=== Was hat gut funktioniert? ===

* Kommunikation - Sowohl die Team interne Kommunikation, als auch die Kommunikation zwischen Auftraggeber und aller am
Projekt beteiligten Personen hat im großen und Ganzen gut funktioniert. Hinsichtlich der Team internen Abstimmungen gibt
es jedoch Verbesserungspotenzial.

* Motivation - Alle Mitglieder waren, trotz div. anderer Verpflichtungen (z.B. Dienstverhältnis) stets motiviert und
daran interessiert diese Projekt best möglich umzusetzen.

=== Was hat schlecht funktioniert? ===

* Zeitenbuchen - Die Zeitaufzeichnungen aller Teammitglieder wurden über ein ERP-System verwaltet. Die Zeiteinteilung
für die übertragenen Aufgaben war bis auf kleine Deadlines völlig frei. Gearbeitet wurde meist allein, selten in
2er Teams. Die Bereitschaft, alle aufgebrachten Zeiten im ERP-System zu buchen war leider eher gering.

*Ressourcenplanung - Der geschätzte bzw. geplante Arbeitsaufwand für einzelne Arbeitsparkete hat sich teilweise als
"falsch" bzw. anders aufgeteilt dargestellt. Dennoch wurde der gesamte Arbeitsauswand für dieses Projekt in etwa
eingehalten.

=== Was kann man aus diesem Projekt für künftige Projekte mitnehmen? ===
* In großen Gruppen schwierig, aber evtl. fixe tage oder Zeiträume, bei denen alle zur gleichen Zeit arbeiten
im Optimalfall am gleichen ort, um Abstimmungen auch kurzfristig machen zu können.

* Projektplanung für Projekte, für welche es keine Erfahrungswerte gibt ist schwierig.
