version: '2'
services:
    ceapp-app:
        image: ceapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ceapp-postgresql:5432/ceapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ceapp-postgresql:
        extends:
            file: postgresql.yml
            service: ceapp-postgresql
